### PR TITLE
Update Info.json

### PR DESCRIPTION
**Pull request by FireController1847**
Update Info.json to the latest version of Ytdl.

### CODE REVIEW

**Comment by fent** [comment]
Thanks for the PR.

Your ip is left in there btw. I usually replace it with `ip=0.0.0.0` but if you don't care I'll merge as is.

Hmm, YouTube seems to change the properties it returns every few days. There's only so much we can do to guarantee certain attributes.

**Comment by FireController1847** [comment]
@fent Yeah. I always forget my IP is in those things haha, thanks for reminding me to remove it.

**Comment by fent** [comment]
You might wanna reset before the last two commits (without undoing the changes), then commit again, and then force push. Otherwise the commits that add/remove your ip will still be there.

**Comment by FireController1847** [comment]
@fent It'll be fine, when I tried to match the IP with the one google gave it was different so, whatever.

**Comment by fent** [comment]
Alright cool. Thanks again.

**Comment by FireController1847** [comment]
No problem! :D

**Pull request merged**
