### PR TITLE
update var to es6

### PR DESCRIPTION
**Pull request by rubs019**
#324 PR of discussion

### CODE REVIEW

**Comment by fent** [comment]
Cool! Do you mind doing this for files in the `test` and `example` folders too? I'd rather handle this change all at once

One more thing, a `.DS_Store` file was added to this PR, please remove.

**Comment by rubs019** [comment]
Yes I can do it
For the .DS_Store I just create a new commit and add DS_Store && .idea in gitignore 

Let me know if it's ok for you

**Comment by fent** [comment]
Thanks for taking the time for this, even though it was probably tedious

**Comment by rubs019** [comment]
No probs, this is my first contribution on an open-source project. I chose something easy and necessary in a certain way ^^

**Pull request merged**
