### PR TITLE
Fix for flagged videos

### PR DESCRIPTION
**Pull request by Bullfrog098**
I'm pretty sure you only need to put it here but i'm not 100% sure, everything works for me after putting this here.

### CODE REVIEW

**Comment by KL13NT** [comment]
I can't verify whether this works or not right now, but I've been getting 410 on literally every video since I woke up today. My code is deployed in a EU region on Heroku.

**Comment by KMoszczyc** [comment]
Damn I'm so waiting for this bug to be fixed :((

**Comment by KAAquilla** [comment]
tried it just now. doesnt work unfortunately. idk why. it should though. if you add "&bpctr=9999999999&has_verified=1" to the URL inside your browser it works. but when trying to request it through ytdl it doesnt work somehow

**Comment by Bullfrog098** [comment]
> tried it just now. doesnt work unfortunately. idk why. it should though. if you add "&bpctr=9999999999&has_verified=1" to the URL inside your browser it works. but when trying to request it through ytdl it doesnt work somehow

**Comment by Bullfrog098** [comment]
oops miss click

**Comment by Bullfrog098** [comment]
> tried it just now. doesnt work unfortunately. idk why. it should though. if you add "&bpctr=9999999999&has_verified=1" to the URL inside your browser it works. but when trying to request it through ytdl it doesnt work somehow

I tested this video out and it also needs a cookie to be able to download for me at least @KAAquilla

**Comment by KAAquilla** [comment]
> > tried it just now. doesnt work unfortunately. idk why. it should though. if you add "&bpctr=9999999999&has_verified=1" to the URL inside your browser it works. but when trying to request it through ytdl it doesnt work somehow
> 
> I tested this video out and it also needs a cookie to be able to download since it is an age-restricted video @KAAquilla
> Videos that are just flagged like https://www.youtube.com/watch?v=hc0ZDaAZQT0 are working with my fix

Yea i specifically wanted to test a video that is flagged and restricted. I am passing cookies btw. Just restricted videos work.

**Comment by Bullfrog098** [comment]
> Yea i specifically wanted to test a video that is flagged and restricted. I am passing cookies btw. Just restricted videos work.

huh really now, I'm getting all my restricted and flagged videos to download. You have any different code or videos that I can test?

**Comment by KMoszczyc** [comment]
Hmm interesting, ytdl-core just started working on restricted videos even without this fix, I just had to add proper cookies to the request. 
example:
const ytdl=require('ytdl-core')
const info = await ytdl.getInfo('https://www.youtube.com/watch?v=ljztzALEqCg',
    {
        requestOptions: {
          headers: {
            Cookie: 'cookie',
            "x-youtube-identity-token": 'yt token'
        }
        }
    });

To get the cookie I used this chrome addon: https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en. After export add '=' in proper places and ';' after every line. So you get something like: 'CONSENT=YES..; VISITORINFO1_LIVE=0_Sha..; PREF=tz=Europe...; ...' etc.

**Comment by Bullfrog098** [comment]
> Hmm interesting, ytdl-core just started working on restricted videos even without this fix, I just had to add proper cookies to the request.
This fix isn't for age-restricted video, it's for videos that are flagged "The following content has been identified by the YouTube community as inappropriate or offensive to some audiences."

**Comment by KAAquilla** [comment]
> 
> 
> Hmm interesting, ytdl-core just started working on restricted videos even without this fix, I just had to add proper cookies to the request.
> example:
> const ytdl=require('ytdl-core')
> const info = await ytdl.getInfo('https://www.youtube.com/watch?v=ljztzALEqCg',
> {
> requestOptions: {
> headers: {
> Cookie: 'cookie',
> "x-youtube-identity-token": 'yt token'
> }
> }
> });
> 
> To get the cookie I used this chrome addon: https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en. After export add '=' in proper places and ';' after every line. So you get something like: 'CONSENT=YES..; VISITORINFO1_LIVE=0_Sha..; PREF=tz=Europe...; ...' etc.

no need for a stupid addon that requires you to re-format everything. Just do CTRL+SHIFT+I inside Chrome/Firefox go to console and enter "document.cookie" -> voila cookies get!

**Comment by Bullfrog098** [comment]
> EDIT: tested it just now again. now age-restricted videos dont work anymore as well. wtf. i will try getting a fresh cookie
> EDIT2: even fresh cookies didnt work now. wtf is this random bullshit

any update on this?

**Comment by Xaypanya** [comment]
The same issue, any solution?

**Comment by KAAquilla** [comment]
> 
> 
> > EDIT: tested it just now again. now age-restricted videos dont work anymore as well. wtf. i will try getting a fresh cookie
> > EDIT2: even fresh cookies didnt work now. wtf is this random bullshit
> 
> any update on this @KAAquilla?

Nope still not working. I feel like its not passing my cookies correctly.

**Comment by Bullfrog098** [comment]
> Nope still not working. I feel like its not passing my cookies correctly.

try only using the cookie "__Secure-3PSID"

**Comment by KAAquilla** [comment]
> 
> 
> > Nope still not working. I feel like its not passing my cookies correctly.
> 
> try only using the cookie "__Secure-3PSID"

still not working. just tried... :/

**Comment by KMoszczyc** [comment]
> > > Nope still not working. I feel like its not passing my cookies correctly.
> > 
> > 
> > try only using the cookie "__Secure-3PSID"
> 
> still not working. just tried... :/
> 
> This is correct how i pass the cookies right? COOKIE and ID_TOKEN are defined above image

Yup looks good. And thanks for the document.cookie trick.

**Comment by Bullfrog098** [comment]
> > > Nope still not working. I feel like its not passing my cookies correctly.
> > 
> > 
> > try only using the cookie "__Secure-3PSID"
> 
> still not working. just tried... :/
> 
> This is correct how i pass the cookies right? COOKIE and ID_TOKEN are defined above image

try without "x-youtube-identity-token"

**Comment by KAAquilla** [comment]
> 
> 
> > This is correct how i pass the cookies right? COOKIE and ID_TOKEN are defined above
> 
> try without "x-youtube-identity-token"

i already did once but tried again now with only 3PSID. same result though. cant find the ID Token
image

**Comment by TimeForANinja** [comment]
should be fixed with #1022 
thanks though for the pr
feel free to reopen if not fixed

**Pull request closed without merging**
