### PR TITLE
fix: Error: Status code: 404

### PR DESCRIPTION
**Pull request by pioneiro**
ytInitialPlayerResponse now contains the video metadata.

### CODE REVIEW

**Comment by jaeblaze1989** [comment]
tested and working with my discord bot.

**Comment by isp96** [comment]
fixed it for me

**Comment by TimeForANinja** [comment]
closing as duplicate of #952

**Comment by CrypticMrDark** [comment]
It fix came 2 days ago.

**Comment by CrypticMrDark** [comment]
This came 2 days ago

**Comment by CrypticMrDark** [comment]
Don't take others code credit

**Pull request closed without merging**
