### PR TITLE
Update info.js

### PR DESCRIPTION
**Pull request by roln21**

### CODE REVIEW

**Comment by roln21** [comment]
DF

**Comment by redbrain** [comment]
The first change isn't necessary if #938 is merged.
The second change is a duplicate of #948 (which is itself a bad version of #946).
Move to close.

**Comment by unclesam1991** [comment]
make it update this bug please

**Comment by TimeForANinja** [comment]
> The first change isn't necessary if #938 is merged.
The second change is a duplicate of #948 (which is itself a bad version of #946).
Move to close.

**Pull request closed without merging**
