### PR TITLE
fix tests on windows

### PR DESCRIPTION
**Pull request by TimeForANinja**

### CODE REVIEW

**Comment by TimeForANinja** [comment]
basicly the same problem as this https://github.com/gotwarlost/istanbul/issues/677

**Comment by TimeForANinja** [comment]
does not look like that works

```js
C:\Users\\Documents\GitHub\node-ytdl-core>npm test

> ytdl-core@0.20.3 test C:\Users\\Documents\GitHub\node-ytdl-core
> istanbul cover mocha -- -t 16000 test/*-test.js

No coverage information was collected, exit without writing coverage information
C:\Users\\Documents\GitHub\node-ytdl-core\node_modules\.bin\mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\\Documents\GitHub\node-ytdl-core\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at runFn (C:\Users\\Documents\GitHub\node-ytdl-core\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
npm ERR! Test failed.  See above for more details.```

**Comment by fent** [comment]
Thanks!

Looks like I'll have to update other repos that use a similar path too.

**Comment by TimeForANinja** [comment]
Np
Interesting how uncommon windows seems to be

**Pull request merged**
