### PR TITLE
Create an Info Example

### PR DESCRIPTION
**Pull request by FireController1847**
Keep this file updated, simply just take a random song and then export ytdl.getInfo to a JSON and post it here.

### CODE REVIEW

**Comment by fent** [comment]
There is currently a linked `info.json` example file linked in the readme
https://github.com/fent/node-ytdl-core/blob/master/README.md#event-info

But I suppose it makes sense to include it in the repo. Do you mind updating the readme link as well?

Also, putting "example" in the filename seems unnecessary when it's already in the example folder.

**Comment by FireController1847** [comment]
@fent Sorry, I'm not exactly the best a GitHub and ended up making another pull request updating the readme. Sorry.

**Comment by fent** [comment]
Are you ok with this file containing your ip? It might be useful to find and replace it with like "0.0.0.0"

**Comment by FireController1847** [comment]
Alright, I removed it.

**Comment by fent** [comment]
Thanks for the PR!

**Comment by FireController1847** [comment]
@fent No problem! :P

**Pull request merged**
