### PR TITLE
Support multiple media objects

### LINKED ISSUE #920: The list of media is not complete.
The media list seems to return only the last one.

Capture d’écran 2021-05-13 à 11 19 38

Capture d’écran 2021-05-13 à 05 31 08

Capture d’écran 2021-05-13 à 05 30 48

— ytdl-core version: `4.7.0`

### PR DESCRIPTION
**Pull request by chrisdeaner**
**NOTE: This could be a breaking change. The proposed type returned is changing from an object to an array.**

Currently the ytdl-core library supports returning a Media object as part of the Video Details. This approach has a couple of issues:

1) When there are multiple songs returned for a video, the Media object can contain information from both songs if the Media attributes are not exactly the same.

Example: Imagine a video contains two songs, Foo and Bar, returned in that order. The Foo song contains only info about the artist, "FooRealz" and the Bar song contains only info about the writer, "BarWritez". Currently the object returned would look like so, squashing the two songs into one:
```json
{
  "media": {
    "song": "Bar"
    "artist": "FooRealz",
    "writers": "BarWritez"
  }
}
```
A good example of this issue can be found here: https://www.youtube.com/watch?v=4bMM7tGV9MI where data from Ozzy Osborn and Ludacris get merged. 

2) Similarly, when videos contain more than one song, all expected information will not be returned.

This PR creates a media array to return all the information present, adds and updates tests, and updates type descriptions. 

Edit:
closes #920

### CODE REVIEW

**Comment by TimeForANinja** [comment]
would be cool to also use this to close #1034

**Comment by chrisdeaner** [comment]
@TimeForANinja - Would be great if this PR helps resolve outstanding issues!

A question about tests: `age_restriction` related tests are failing for me. Specifically "Returns correct video metainfo" and "Returns correct age_restricted property in other languages". I see that you released 4.11.0 yesterday with some `age_restriction` changes. Are these test failures expected or should I take these failures as an issue with my code / environment? 

Any help is appreciated.

**Comment by TimeForANinja** [comment]
i added some messages to identify the failing assertions
unfortunately you broke [this](https://github.com/chrisdeaner/node-ytdl-core/blob/multiple-media-tags/lib/info.js#L88) part of the original code with your changes

guess it has to do with not pushing `media` into `medias` after every iteration of [this](https://github.com/chrisdeaner/node-ytdl-core/blob/multiple-media-tags/lib/info-extras.js#L38) for loop? though i must say i'm not quite sure what these 
````js
if (title === 'song') {
          media = {};
          medias.push(media);
        }
```
are supposed to achieve any way 😅

**Comment by chrisdeaner** [comment]
@TimeForANinja Thanks for adding that messaging and for your comments; very helpful. I pushed some changes and all the tests are now passing. As for the the blocks of code with `title === 'song'`, they designate when the information for a song is starting. I could see no other way where the data indicates that it contained discrete song information. This approach works consistently in my tests. 

Looking forward to getting this in! Thanks for your help and review!

**Comment by absidue** [comment]
@chrisdeaner As you are checking for the title in English this PR only works if the `lang` option is set to `en` or left blank (the default value of the `lang` option is `en`).

**Comment by chrisdeaner** [comment]
@absidue that makes perfect sense. I'm going to close this PR for now and reassess the approach. I'm not very familiar with this library so if you can think of any viable approaches, feel free to drop them in this PR and I'll look into it.

**Pull request closed without merging**
