### PR TITLE
Update getWatchHTMLPage right pos

### PR DESCRIPTION
**Pull request by mome0320**
in WatchHTMLPage
info.response isn't end `\n` (it's last line)
so update right pos `</script>` is better.

In test I think it works.
image

### CODE REVIEW

**Review by RisedSky — APPROVED** [review]
This fix the issue using ytdl-core for Discord music bot

**Comment by TimeForANinja** [comment]
🤔 can't replicate
can you provide me with a watchHTMLPage you receive?
a simple `fs.writeFileSync` befor the line you edited should do it

**Review by RisedSky — COMMENTED** [review]
This doesn't fix, getting the following error after playing the song : 

```stack: 'Error: aborted\n    at connResetException (node:internal/errors:683:14)\n    at TLSSocket.socketCloseListener (node:_http_client:407:19)\n    at TLSSocket.emit (node:events:406:35)\n    at node:net:661:12\n    at TCP.done (node:_tls_wrap:580:7)\n    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)'```

**Comment by mome0320** [comment]
>  can't replicate
> can you provide me with a watchHTMLPage you receive?
> a simple `fs.writeFileSync` befor the line you edited should do it

https://gist.github.com/mome0320/5ef235f47239a2dcb90f35baa79daa3c
here this file.

**Comment by mome0320** [comment]
> This doesn't fix, getting the following error after playing the song :
> 
> `stack: 'Error: aborted\n at connResetException (node:internal/errors:683:14)\n at TLSSocket.socketCloseListener (node:_http_client:407:19)\n at TLSSocket.emit (node:events:406:35)\n at node:net:661:12\n at TCP.done (node:_tls_wrap:580:7)\n at TCP.callbackTrampoline (node:internal/async_hooks:130:17)'`

this PR may not affect error this.

**Comment by TimeForANinja** [comment]
any reason for not moving all three findJSON to `'</script>'` ?
besides that this pr looks fine - already thanks for the time 😉

**Comment by mome0320** [comment]
> any reason for not moving all three findJSON to `'</script>'` ?
> besides that this pr looks fine - already thanks for the time

in 318 line?
```js
  try {
    info.player_response = findJSON('watch.html', 'player_response',
      body, /\bytInitialPlayerResponse\s*=\s*\{/i, '\n', '{'); // this?
  } // ...
```
It works even if you don't change this line
but move all end '</script>' is fine for me.

**Comment by TimeForANinja** [comment]
> but move all end '</script>' is fine for me.

let's do it then
don't wanna touch this code again in the next months 😂

**Comment by TimeForANinja** [comment]
nice - tests are passing
gonna wait for https://github.com/fent/node-ytdl-core/pull/938 to be ready to merge before merging this...
will only confuse ppl when we bring half an update now...

**Comment by TimeForANinja** [comment]
Thanks again for the PR @mome0320  and everyone else who helped
For further Problems with (especially) video details check out https://github.com/fent/node-ytdl-core/issues/958

**Pull request merged**
