### PR TITLE
fix: add html5 param to fetching of VideoInfoPage

### LINKED ISSUE #923: ytdl.getInfo - Error: Status code: 404
The problem is that if i try get info from some urls i get this error. Example below. 

```
const customVideoInfo = await ytdl.getInfo("http://www.youtube.com/watch?v=3Z61pOtkY7w")

Error: Status code: 404
    at ClientRequest.<anonymous> (/workspace/node_modules/miniget/dist/index.js:211:27)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:506:15)
    at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:506:15) 
```

### PR DESCRIPTION
**Pull request by vaaski**
this makes age-restricted videos work again, although quite slow.
it also fixes the test for age restricted videos, as the old one was deleted.

### CODE REVIEW

**Comment by vaaski** [comment]
@fent I'd love to get this merged to at least restore functionality for age-restricted videos.

**Comment by TimeForANinja** [comment]
I'll have a look later this week when I get home...

**Comment by vaaski** [comment]
perfect, thanks.

**Comment by TimeForANinja** [comment]
ok
can replicate both the problem and the solution 👍

**Pull request merged**
