### PR TITLE
feat: expose version

### PR DESCRIPTION
**Pull request by TimeForANinja**
the package.json of a submodule is hard to reach
that's all i'll say

### CODE REVIEW

**Comment by fent** [comment]
if this is for the auto-updater, i don't think exposing `version` can help with arbitrary modules. i was looking at the node modules API, there's `Module._resolveFilename`(not documented, so may be unavailable in the future), and `new Module(Module._resolveFilename('ytdl-core')).path` which returns the absolute path of a required file.

after you have the path, you can use something like https://www.npmjs.com/package/find-root

**Comment by TimeForANinja** [comment]
that's basically my current approach - just without any dependencies and using `require.cache[require.resolve(xxx))` instead of `Module_resolveFilename` which i'm unable to find

that updater has some bigger design challenges with updating sub-dependencies, removing deleted files, handling non-github-repositories and so on....

exposing version was just a nice-to-have for some minor projects i run
not forcing everyone to use complex methods for reaching the package.json

**Comment by fent** [comment]
where do we stand on this?

**Comment by TimeForANinja** [comment]
🤷🏿 i'm still in favor as a nice-to-have
but i don't mind not adding it

**Pull request merged**
