### PR TITLE
This fixes my issues.

### PR DESCRIPTION
**Pull request by Megalodon-sharky**

### CODE REVIEW

**Comment by skick1234** [comment]
This is the correct way to fix the problem. Not just copy a workaround on the internet and make a pull request. 

https://github.com/fent/node-ytdl-core/pull/938

**Comment by D3SOX** [comment]
Yes, this is a duplicate of #946. Can probably be closed, the branch doesn't even exist anymore.

**Comment by TimeForANinja** [comment]
@Megalodon-sharky thanks for the PR
can you pls check if https://github.com/fent/node-ytdl-core/pull/946 does the job for you?

**Comment by Megalodon-sharky** [comment]
> @Megalodon-sharky thanks for the PR
> can you pls check if #946 does the job for you?

Well, I use heroku, and I also use distube. If I do install this, it will install in node_modules. Where I really need it installed is in /node_modules/distube/node_modules. I'm really not sure how to do that on heroku and make it work but yea. I tested it on my PC where I made the changes manually and it worked. Still sad about how to fix the heroku thing

**Comment by konsumer** [comment]
Yeh, this just overrides what `findJSON` does (skipping it's params completely.)

If you want the fix in your heroku app, in node_modules, a better temporary solution (until it is merged & published in this library, on npm) would be to use @D3SOX PR, directly:

```
npm i git://github.com/D3SOX/node-ytdl-core#fix-info-endpoint-404
```

**Comment by Megalodon-sharky** [comment]
> Yeh, this just overrides what `findJSON` does (skipping it's params completely.)
> 
> If you want the fix in your heroku app, in node_modules, a better temporary solution (until it is merged & published in this library, on npm) would be to use @D3SOX PR, directly:
> 
> ```
> npm i git://github.com/D3SOX/node-ytdl-core#fix-info-endpoint-404
> ```

But I don't know how to specify the path in heroku because inside node_modules, there is distube, the package I use and under distube there is another node_modules that contains ytdl-core.

**Comment by konsumer** [comment]
@MadLittleMods this will add it to your package.json, which tells heroku what to install in node_modules. Because the parent project has it as a dep, it should use that instead of the version marked in distube. Try it. It should work. I'd have to see your project layout to really troubleshoot, but that is how it's meant to work. Or alternately, you could wait for it to be merged.

**Comment by TimeForANinja** [comment]
closing since #946 was merged

**Pull request closed without merging**
