### PR TITLE
more efficient and should stop 429

### PR DESCRIPTION
**Pull request by twarped**
it doesn't manage the audio format. but I think you can do that. but it should stop 429 too many requests. I'm going to keep trying it out, we'll see what happens.

### CODE REVIEW

**Comment by redbrain** [comment]
As of Feb 11th 2020, `request` (a dependency in this PR) is fully deprecated and should NOT be used.
I move to close.

**Comment by twarped** [comment]
what would you suggest using?

**Comment by fent** [comment]
does this stop 429 for you?

**Comment by redbrain** [comment]
> what would you suggest using?

miniget (the current requesting library) is currently serving very well, and fits ytdl-core's use case perfectly.
However, if you can confirm that `request` or another libary would stop 429s, or if you can adapt your code to be used with miniget, it's worth a try. Please follow up with more information on if this could be safely implemented.

**Comment by twarped** [comment]
So far it has worked for me and I haven't gotten 429. I'll look into miniget, thanks for the tip.

**Comment by twarped** [comment]
I successfully switched to miniget

**Comment by twarped** [comment]
You can now watch this in a webpage, (so no ads for the video you're watching), if you don't have the content disposition header, and it's so much faster than my original solution, thanks to the existing ytdl-core.getInfo api.

**Comment by twarped** [comment]
https://glitch.com/edit/#!/tattered-lead-archaeopteryx?path=server.js%3A57%3A33 for code i'm using

**Comment by mh4ck** [comment]
Hahaha, please remove it :D

**Comment by twarped** [comment]
what's pr?

**Comment by redbrain** [comment]
This destroys existing functionality and does not appear to prevent ratelimiting whatsoever.
It would be nice if someone more familiar with ytdl-core could confirm that though, or at least make the PR usable.

**Comment by twarped** [comment]
umm okay

**Comment by twarped** [comment]
but im gonna use this for my own purposes if that's okay

**Pull request closed without merging**
