### PR TITLE
Problem with key valid returning error

### PR DESCRIPTION
**Pull request by Santimto**

### CODE REVIEW

**Comment by fent** [comment]
Could you post a video where the `key` isn't found?

**Comment by Santimto** [comment]
https://www.youtube.com/watch?v=_OPTyIrhwX8
https://www.youtube.com/watch?v=pAzaqRpmAGc
https://www.youtube.com/watch?v=bAu6d0r50iY

**Comment by fent** [comment]
I'm still able to parse a `key` with all of those videos. And I don't get the point of negating the `key` check, if you look at the travis-ci builds, the tests fail.

But I do think the change has a point, we don't have to check if `key` is defined or not.

**Comment by Santimto** [comment]
I'm using in my company's application with this change and stopped giving errors ... without it's common error: Could not extract signature deciphering actions that force restart of the application.

**Comment by fent** [comment]
Are you sure fixing that error isn't from a recent release that fixes it?

https://github.com/fent/node-ytdl-core/commit/18b3f22ca14b6ee61bc646fd8a2f2c943baa6709

**Comment by Santimto** [comment]
Fixed in last update! Thanks =)

**Pull request closed without merging**
