### PR TITLE
Move Readme "Tags"

### PR DESCRIPTION
**Pull request by FireController1847**
Move readme tags to the right of the title like every other library lol

(imho it looks easier to read and cuts off the text less)

### CODE REVIEW

**Comment by fent** [comment]
I used to put the badges next to the module name long ago. But I moved them to after the short description, mainly because I thought the description was more important to immediately see when scrolling down, compared to the badges.

It's also easier to edit badges if they're on separate lines. Might still be able to do this and at the same time make them show up next to the name, not sure.

**Comment by FireController1847** [comment]
I see where you're going and I totally understand, although I think in their current position the badges are more distracting than they would be as if they were next to the title. For a couple reasons, the main one being that since everyone is already used to it being next to the title they tend to get ignored. Right now, they actually _cut off_ the description abruptly, and while I was reading I lost my place and was discouraged to continue reading (hence the creation of this PR).

**Comment by fent** [comment]
Hmm, ok. How about placing them right below the name, each on their own line for easier editing.

**Comment by FireController1847** [comment]
I tried that but for some reason it put them all on separate lines

**Comment by fent** [comment]
How about like this? They're on separate lines in the file, but show up on the same line rendered.

**Comment by FireController1847** [comment]
Looks good to me. It doesn't cut off the description and is still very smooth to read.

**Comment by fent** [comment]
Great, and thanks again!

**Pull request merged**
